version: "3.9"

services:
  ffmpeg-test:
    build:
      context: ..
      dockerfile: Deploy/Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"

    container_name: ffmpeg_test

#    extra_hosts:
#          - "host.docker.internal:host-gateway"

    volumes:
      - ../movie_test1.mp4:/data/input.mp4:ro
      - ../frames_test:/out

    tty: true
